config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'welcome#index'

  resources :users, only: [:show]
  resources :books, :interests, :authors, :publishers, :comments

  resources :comments, only: [:new, :create, :edit, :update, :destroy]

  resources :books do
    resources :interests, only: [:new]
  end

  resources :interests do
    resources :comments, only: [:new]
  end

end

app/models/author.rb
class Author < ActiveRecord::Base

  has_many :book_and_author_links, dependent: :destroy
  has_many :books, through: :book_and_author_links

  validates :first_name, presence: true
  validates :last_name, presence: true

  def short_name
    "#{self.first_name.first}. #{self.last_name}"
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  load_and_authorize_resource :Author
  before_action :find_author, only: [:show, :edit, :update, :destroy]

  def index
    @q = Author.ransack(params[:q])
    @authors = @q.result.paginate(:page => params[:page], :per_page => 2)
  end

  def new
    @author = Author.new
  end

  def create
    data = params.require(:author).permit(:first_name, :last_name)
    @author = Author.new(data)
    if @author.save
      redirect_to authors_path
    else
      render :new
    end
  end

  def update
    data = params.require(:author).permit(:first_name, :last_name)
    if @author.update(data)
      redirect_to authors_path
    else
      render :edit
    end
  end

  def edit
  end

  def show
  end

  def destroy
    @author.destroy
    redirect_to authors_path
  end

  private

  def find_author
    @author = Author.find(params[:id])
  end

end

app/views/authors/edit.html.erb
<% content_for :h2 do %>
	<%= I18n.t("author.edit") %>
<% end %>
<% content_for :submit do %>
	<%= I18n.t("author.edit_action") %>
<% end %>
<%= render template: "authors/new-edit-form" %>

app/views/authors/index.html.erb
<% if user_signed_in? %>
  <%= link_to I18n.t('author.new'), new_author_path, class: 'btn btn-primary' %>
<% else %>
  <%= link_to I18n.t('author.sign_in_to_new'), new_user_session_path, :class => "btn btn-primary" %>
<% end %>

<%= search_form_for @q, :html => {:class => 'form-inline pull-right'} do |f| %>
  <div class="form-group">
    <%= f.label :name_cont, :class => "sr-only" %>
    <%= f.search_field :first_name_or_last_name_cont, :class => "form-control" %>
   </div>

  <%= f.submit I18n.t('author.search'), :class => "btn btn-primary" %>
<% end %>

<ul>
  <% @authors.each do |a| %>
    <li>
      <%= link_to author_path(a) do %>
        <%= a.first_name %>
        <%= a.last_name %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate @authors, renderer: BootstrapPagination::Rails %>

app/views/authors/new-edit-form.html.erb
<% if user_signed_in? %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h2><%= yield :h2 %></h2>

      <%= form_for(@author) do |f| %>

        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: "form-control", placeholder: "", required: true %>
        </div>

        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: "form-control", placeholder: "", required: true %>
        </div>

        <div class="form-group">
          <%= f.submit (yield :submit), class: "btn btn-primary" %>
        </div>
      <% end %>

      <%= link_to I18n.t('author.link_to_index'), authors_path %>
    </div>
  </div>
<% end %>

app/views/authors/new.html.erb
<% content_for :h2 do %>
  <%= I18n.t("author.new") %>
<% end %>
<% content_for :submit do %>
  <%= I18n.t("author.new_action") %>
<% end %>
<%= render template: "authors/new-edit-form" %>

app/views/authors/show.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h2><%= I18n.t('author.show') %></h2>
    <h3>
      <%= @author.first_name %>
      <%= @author.last_name %>
    </h3>

    <ul>
      <% @author.books.each do |b| %>
        <li>
          <%= link_to b.name, book_path(b) %>
        </li>
      <% end %>
    </ul>

    <% if user_signed_in? %>
      <p>
        <% if can? :update, @author %>
          <%= link_to I18n.t('author.edit_action'), edit_author_path(@author),  class: "btn btn-default" %>
        <% end %>
        <% if can? :destroy, @author %>
          <%= button_to I18n.t('author.drop_action'), author_path(@author), data: { confirm: I18n.t('author.drop_confirm') }, method: :delete, class: "btn btn-danger" %>
        <% end %>
      </p>
    <p>
      <% else %>
        <%= link_to I18n.t('author.sign_in_to_edit'), new_user_session_path, :class => "btn btn-primary" %>
      <% end %>
    </p>

    <%= link_to I18n.t('author.link_to_index'), authors_path %>
  </div>
</div>