config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'welcome#index'

  resources :users, only: [:show]
  resources :books, :interests, :authors, :publishers, :comments

  resources :comments, only: [:new, :create, :edit, :update, :destroy]

  resources :books do
    resources :interests, only: [:new]
  end

  resources :interests do
    resources :comments, only: [:new]
  end

end

app/models/interest.rb
class Interest < ActiveRecord::Base

  belongs_to :user
  belongs_to :book
  has_many :comments, dependent: :destroy

  validates :user_id, presence: true

  default_scope -> { order('created_at DESC') }

end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController

  load_and_authorize_resource param_method: :interest_params
  before_action :find_interest, only: [:show, :edit, :update, :destroy]
  before_action :correct_user,  only: [:edit, :update,:destroy]

  def show
  end

  def new
    @interest = Interest.new
    if(params[:book_id])
      @interest.book = Book.find(params[:book_id])
    end
  end

  def create
    @interest = current_user.interests.build(interest_params)
    if @interest.save
      redirect_to current_user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @interest.update_attributes(interest_params)
      redirect_to current_user
    else
      render 'edit'
    end
  end

  def destroy
    @interest.destroy
    redirect_to current_user
  end

  private

    def interest_params
      params.require(:interest).permit(:user_id, :book_id, :review, :start_reading, :finish_reading)
    end

    def find_interest
      @interest = Interest.find(params[:id])
    end

    def correct_user
      @interest = current_user.interests.find_by(id: params[:id])
      redirect_to root_url if @interest.nil?
    end

end

app/views/interests/_fields.html.erb
<div class="form-group">
  <%= f.label :book_id %>
  <%= link_to I18n.t('interest.new_book'), new_book_path, :class => "pull-right" %>
  <%= f.collection_select(:book_id, Book.all, :id, :name, {}, {:class=>"form-control selectpicker", :required => true, :title => I18n.t('interest.select_books_title') }) %>
</div>

<div class="form-group">
  <%= f.label :review %>
  <%= f.text_area :review, class: "form-control", placeholder: "" %>
</div>

<div class="form-group">
  <%= f.label :start_reading %>
  <%= f.date_field :start_reading, class: "form-control", placeholder: "" %>
</div>

<div class="form-group">
  <%= f.label :finish_reading %>
  <%= f.date_field :finish_reading, class: "form-control", placeholder: "" %>
</div>

app/views/interests/edit.html.erb
<% if user_signed_in? %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h2><%= I18n.t("interest.edit") %></h2>

      <%= form_for(@interest) do |f| %>

        <%= render 'fields', f: f %>

        <div class="form-group">
          <%= f.submit I18n.t("interest.edit_action"), class: "btn btn-primary" %>
        </div>
      <% end %>

      <%= link_to I18n.t('interest.link_to_index'), current_user %>
    </div>
  </div>
<% end %>

app/views/interests/index.html.erb
<h1>Interests</h1>
<p>Find me in app/views/interests/index.html.erb</p>

app/views/interests/new.html.erb
<% if user_signed_in? %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h2><%= I18n.t("interest.new") %></h2>

      <%= form_for(@interest) do |f| %>

        <%= render 'fields', f: f %>

        <div class="form-group">
          <%= f.submit I18n.t("interest.new_action"), class: "btn btn-primary" %>
        </div>
      <% end %>

      <%= link_to I18n.t('interest.link_to_index'), current_user %>
    </div>
  </div>
<% end %>

app/views/interests/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2><%= I18n.t('interest.show') %></h2>

    <dl class="dl-horizontal">
      <dt>
        <%= Interest.human_attribute_name(:book) %>
      </dt>
      <dd>
        <%= link_to book_path(@interest.book) do %>
          <%= @interest.book.name %>
        <% end %>
      </dd>
      <dt>
        <%= Interest.human_attribute_name(:review) %>
      </dt>
      <dd>
        <%= @interest.review %>
      </dd>
      <% if @interest.start_reading? %>
        <dt>
          <%= Interest.human_attribute_name(:start_reading) %>
        </dt>
        <dd>
            <%= @interest.start_reading.strftime('%e %B %Y') %>
        </dd>
      <% end %>
      <% if @interest.finish_reading? %>
        <dt>
        <%= Interest.human_attribute_name(:finish_reading) %>
        </dt>
        <dd>
          <%= @interest.finish_reading.strftime('%e %B %Y') %>
        </dd>
      <% end %>
    </dl>

    <% if user_signed_in? %>
      <p>
        <% if can? :update, @interest %>
          <%= link_to I18n.t('interest.edit_action'), edit_interest_path(@interest),  class: "btn btn-default" %>
        <% end %>
        <% if can? :destroy, @interest %>
          <%= button_to I18n.t('interest.drop_action'), interest_path(@interest), data: { confirm: I18n.t('interest.drop_confirm') }, method: :delete, class: "btn btn-danger" %>
        <% end %>
      </p>
    <p>
      <% else %>
        <%= link_to I18n.t('interest.sign_in_to_edit'), new_user_session_path, :class => "btn btn-primary" %>
      <% end %>
    </p>

    <% if user_signed_in? %>
      <%= link_to I18n.t('interest.link_to_index'), current_user %>
    <% end %>

    <h3><%= I18n.t('interest.comments') %></h3>

    <ul class="comment-list">
      <% @interest.comments.each do |comment| %>
        <li class="comment">
          <div class="comment-info">
            <%= link_to comment.user.full_name, user_path(comment.user) %>
            <div class="comment-date"><%= comment.created_at.strftime('%e %B %Y в %H:%M') %></div>
          </div>
          <div class="comment-content">
            <% if can? :update, comment %>
              <%= button_to I18n.t('comment.drop_action'), comment_path(comment), method: :delete, class: "btn btn-danger pull-right" %>
            <% end %>
            <% if can? :destroy, comment %>
              <%= button_to I18n.t('comment.edit_action'), edit_comment_path(comment), method: :get, class: "btn btn-warning pull-right" %>
            <% end %>
            <%= comment.content %>
            <div class="clearfix"></div>
          </div>
        </li>
      <% end %>
    </ul>

    <p>
      <%= link_to new_interest_comment_path(@interest) do %>
        <%=  I18n.t('interest.new_comment') %>
      <% end %>
    </p>

    <% if @interest.comments.length > 0 %>
      <%= pie_chart @interest.comments.joins(:user).group("users.last_name").count %>
    <% else %>
      <p>
        <%= I18n.t('interest.no_comments') %>
      </p>
    <% end %>

  </div>
</div>