config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'welcome#index'

  resources :users, only: [:show]
  resources :books, :interests, :authors, :publishers, :comments

  resources :comments, only: [:new, :create, :edit, :update, :destroy]

  resources :books do
    resources :interests, only: [:new]
  end

  resources :interests do
    resources :comments, only: [:new]
  end

end

app/models/book.rb
class Book < ActiveRecord::Base

  belongs_to :publisher
  has_many   :interests, dependent: :destroy
  has_many   :users, through: :interests
  has_many   :book_and_author_links, dependent: :destroy
  has_many   :authors, through: :book_and_author_links

  def author_short
    author = self.authors.first
    "#{author.first_name.first}. #{author.last_name}"
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  load_and_authorize_resource :Book, through: :interests
  before_action :find_book, only: [:show, :edit, :update, :destroy]

  def index
    @q = Book.ransack(params[:q])
    @books = @q.result.paginate(:page => params[:page], :per_page => 2)
  end

  def new
    @book = Book.new
  end

  def create
    data = params.require(:book).permit(:name, :genre, :publisher_id, :page_count, :author_ids)
    @book = current_user.books.new(data)
    if @book.save
      params[:book][:author_ids].each do |id|
        BookAndAuthorLink.create({book: @book, author: Author.find(id), role: :author}) if id.to_i > 0
      end
      redirect_to books_path
    else
      render :new
    end
  end

  def update
    data = params.require(:book).permit(:name, :genre, :publisher_id, :page_count, :author_ids)
    if @book.update(data)
      @book.book_and_author_links.delete_all
      params[:book][:author_ids].each do |id|
        BookAndAuthorLink.create({book: @book, author: Author.find(id), role: :author}) if id.to_i > 0
      end
      redirect_to books_path
    else
      render :edit
    end
  end

  def edit
  end

  def show
    @timeline = @book.interests
    .select do |i|
      i.start_reading && i.finish_reading
    end
    .map do |i|
      username = i.user.short_name
      from = i.start_reading.to_s
      to = i.finish_reading.to_s
      [username, from, to]
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def find_book
    @book = Book.find(params[:id])
  end

end

app/views/books/edit.html.erb
<% content_for :h2 do %>
	<%= I18n.t("book.edit") %>
<% end %>
<% content_for :submit do %>
	<%= I18n.t("book.edit_action") %>
<% end %>
<%= render template: "books/new-edit-form" %>

app/views/books/index.html.erb
<% if user_signed_in? %>
  <%= link_to I18n.t('book.new'), new_book_path, class: 'btn btn-primary' %>
<% else %>
  <%= link_to I18n.t('book.sign_in_to_new'), new_user_session_path, :class => "btn btn-primary" %>
<% end %>

<%= search_form_for @q, :html => {:class => 'form-inline pull-right'} do |f| %>
  <div class="form-group">
    <%= f.label :name_cont, :class => "sr-only" %>
    <%= f.search_field :name_cont, :class => "form-control" %>
   </div>

  <%= f.submit I18n.t('book.search'), :class => "btn btn-primary" %>
<% end %>

<table class="table">

  <thead>
    <tr>
      <td>
        <%= Book.human_attribute_name(:name) %>
      </td>
      <td>
        <%= Book.human_attribute_name(:author_short) %>
      </td>
      <td>
        <%= Book.human_attribute_name(:genre) %>
      </td>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |b| %>
      <tr>
        <td>
          <%= link_to b.name, book_path(b) %>
        </td>
        <td>
          <%= b.author_short %>
        </td>
        <td>
          <%= b.genre %>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>

<%= will_paginate @books, renderer: BootstrapPagination::Rails %>

app/views/books/new-edit-form.html.erb
<% if user_signed_in? %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h2><%= yield :h2 %></h2>

      <%= form_for(@book) do |f| %>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control", placeholder: "", required: true %>
        </div>

        <div class="form-group">
          <%= f.label :author_ids %>
          <%= link_to I18n.t('book.new_author'), new_author_path, :class => "pull-right" %>
          <%= f.collection_select(:author_ids, Author.all, :id, :short_name, {}, {:class=>"form-control selectpicker", :required => true, :multiple => true, :title => I18n.t('book.select_authors_title') }) %>
        </div>

        <div class="form-group">
          <%= f.label :genre %>
          <%= f.text_field :genre, class: "form-control", placeholder: "" %>
        </div>

        <div class="form-group">
          <%= f.label :publisher_id %>
          <%= link_to I18n.t('book.new_publisher'), new_publisher_path, :class => "pull-right" %>
          <%= f.collection_select(:publisher_id, Publisher.all, :id, :name, {}, {:class=>"form-control selectpicker", :title => I18n.t('book.select_publisher_title') }) %>
        </div>

        <div class="form-group">
          <%= f.label :page_count %>
          <%= f.number_field :page_count, class: "form-control", placeholder: "" %>
        </div>

        <div class="form-group">
          <%= f.submit (yield :submit), class: "btn btn-primary" %>
        </div>
      <% end %>

      <%= link_to I18n.t('book.link_to_index'), books_path %>
    </div>
  </div>
<% end %>

app/views/books/new.html.erb
<% content_for :h2 do %>
	<%= I18n.t("book.new") %>
<% end %>
<% content_for :submit do %>
	<%= I18n.t("book.new_action") %>
<% end %>
<%= render template: "books/new-edit-form" %>

app/views/books/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2><%= I18n.t('book.show') %></h2>

    <dl class="dl-horizontal">
      <dt>
        <%= Book.human_attribute_name(:name) %>
      </dt>
      <dd>
        <%= @book.name %>
      </dd>
      <dt>
        <%= Book.human_attribute_name(:authors) %>
      </dt>
      <dd>
        <% @book.authors.each do |a| %>
          <%= link_to author_path(a) do %>
            <%= a.first_name %>
            <%= a.last_name %>
          <% end %>
          <br />
        <% end %>
      </dd>
      <dt>
        <%= Book.human_attribute_name(:genre) %>
      </dt>
      <dd>
        <%= @book.genre %>
      </dd>
      <% if @book.publisher %>
        <dt>
          <%= Book.human_attribute_name(:publisher) %>
        </dt>
        <dd>
          <%= link_to publisher_path(@book.publisher) do %>
            <%= @book.publisher.name %>
          <% end %>
        </dd>
      <% end %>
      <dt>
        <%= Book.human_attribute_name(:page_count) %>
      </dt>
      <dd>
        <%= @book.page_count %>
      </dd>
      <dt>
        <%= I18n.t('book.interests') %>
      </dt>
      <dd>
        <% @book.interests.each do |interest| %>
          <%= link_to interest_path(interest) do %>
            <%= interest.user.first_name %>
            <%= interest.user.last_name %>
          <% end %>
          <br />
        <% end %>
        <%= link_to new_book_interest_path(@book) do %>
          <%=  I18n.t('book.new_interest') %>
        <% end %>
      </dd>
    </dl>

    <% if user_signed_in? %>
      <p>
        <% if can? :update, @book %>
          <%= link_to I18n.t('book.edit_action'), edit_book_path(@book),  class: "btn btn-default" %>
        <% end %>
        <% if can? :destroy, @book %>
          <%= button_to I18n.t('book.drop_action'), book_path(@book), data: { confirm: I18n.t('book.drop_confirm') }, method: :delete, class: "btn btn-danger" %>
        <% end %>
      </p>
    <p>
      <% else %>
        <%= link_to I18n.t('book.sign_in_to_edit'), new_user_session_path, :class => "btn btn-primary" %>
      <% end %>
    </p>

    <p>
      <%= link_to I18n.t('book.link_to_index'), books_path %>
    </p>

    <% if @timeline.length > 0 %>
      <%= timeline @timeline %>
    <% else %>
      <p>
        <%= I18n.t('book.no_interests') %>
      </p>
    <% end %>

  </div>
</div>